version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d    
    restart: always

  web:
    build: ./src
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes: 
      - ./src:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
    restart: always
