# Generated by Django 2.1.11 on 2019-09-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
