# Generated by Django 2.1.11 on 2019-09-19 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190916_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
